name: "Auto Merge Branch"
description: "A GitHub Action to automatically merge two branches using the GitHub REST API"
author: Lee Lott

inputs:
  repo-name:
    description: 'The name of the repository'
    required: true
  org-name:
    description: 'The name of the GitHub organization'
    required: true
  source-branch:
    description: 'The branch you want to merge from (head)'
    required: true
  target-branch:
    description: 'The branch you want to merge into (base)'
    required: true    
  token:
    description: 'GitHub token with access to pull requests'
    required: true

outputs:
  result:
    description: 'Result of the attempt to update the Pull Request Status ("success" or "failure")'
    value: ${{ steps.return-result.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Create Pull Request
      id: create-pr
      uses: lee-lott-actions/create-pull-request@v1
      with:
        source-branch: ${{ inputs.source-branch }}
        target-branch: ${{ inputs.target-branch }}
        pr-title: '[Automated] Merge ${{ inputs.source-branch }} into ${{ inputs.target-branch }}'
        pr-body: |
          This pull request was automatically generated by a GitHub Action.

          - **Source branch:** `${{ inputs.source-branch }}`
          - **Target branch:** `${{ inputs.target-branch }}`

          ### Purpose

          This PR merges changes from the source branch into the target branch to keep them in sync.
        org-name: ${{ inputs.org-name }}
        repo-name: ${{ inputs.repo-name }}
        token: ${{ inputs.token }}

    - name: Comment on Pull Request
      if: ${{ steps.create-pr.outputs.result == 'success' }}
      id: comment-pr
      uses: lee-lott-actions/set-pull-request-review-status@v1
      with:
        pr-number: ${{ steps.create-pr.outputs.pr-number }}
        repo-name: ${{ inputs.repo-name }}
        org-name: ${{ inputs.org-name }}
        pr-status: 'COMMENT'
        pr-message: 'This PR was approved automatically as part of the branch synchronization process.'
        token: ${{ inputs.token }}

    - name: Merge Pull Request
      if: ${{ steps.comment-pr.outputs.result == 'success' }}
      id: merge-pr
      uses: lee-lott-actions/merge-pull-request@v1
      with:
        pr-number: ${{ steps.create-pr.outputs.pr-number }}
        repo-name: ${{ inputs.repo-name }}
        org-name: ${{ inputs.org-name }}
        merge-type: 'merge'
        merge-title-message: 'chore: Automatically merged for branch synchronization.'
        token: ${{ inputs.token }}

    - name: Return Result
      if: always()
      id: return-result
      shell: pwsh
      run: |
        if ($env:JOB_STATUS -ne "success") {
          $MESSAGE = "❌ Failed to merge pull request. Check the workflow logs for details."
          $RESULT = "failure"
        } elseif ("${{ steps.create-pr.outputs.result }}" -ne "success") {
          $MESSAGE = "❌ Failed to create pull request. Error: ${{ steps.create-pr.outputs.error-message }}"
          $RESULT = "failure"
        } elseif ("${{ steps.comment-pr.outputs.result }}" -ne "success") {
          $MESSAGE = "❌ Failed to comment on pull request. Error: ${{ steps.comment-pr.outputs.error-message }}"
          $RESULT = "failure"
        } elseif ("${{ steps.merge-pr.outputs.result }}" -ne "success") {
          $MESSAGE = "❌ Failed to merge pull request. Error: ${{ steps.merge-pr.outputs.error-message }}"
          $RESULT = "failure"
        } else {
          $MESSAGE = "✅ Successfully merged pull request"
          $RESULT = "success"
        }
        
        # Write message to workflow log
        Write-Host $MESSAGE

        # Output for GitHub Actions
        "result=$RESULT"  | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      env:
        JOB_STATUS: ${{ job.status }}
        